version: 2
jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: |
          docker buildx build \
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
            --tag petercb/dragonfly-mc .